CREATE DATABASE IF NOT EXISTS wastemanagment
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE wastemanagment;

CREATE TABLE IF NOT EXISTS admins (
  admin_id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(150) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS restaurants (
  restaurant_id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(150) NOT NULL,
  email VARCHAR(150) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  latitude DECIMAL(10,7) NOT NULL DEFAULT 0,
  longitude DECIMAL(10,7) NOT NULL DEFAULT 0,
  closing_time TIME NOT NULL DEFAULT '23:59:59'
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS ngos (
  ngo_id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(150) NOT NULL,
  email VARCHAR(150) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  latitude DECIMAL(10,7) NOT NULL DEFAULT 0,
  longitude DECIMAL(10,7) NOT NULL DEFAULT 0
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS food_items (
  food_item_id INT AUTO_INCREMENT PRIMARY KEY,
  restaurant_id INT NOT NULL,
  food_name VARCHAR(200) NOT NULL,
  servings INT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  expires_at DATETIME NOT NULL,
  status ENUM('listed','accepted','claimed','picked_up','rejected','expired') NOT NULL DEFAULT 'listed',
  CONSTRAINT fk_food_restaurant FOREIGN KEY (restaurant_id)
    REFERENCES restaurants(restaurant_id) ON DELETE CASCADE,
  INDEX idx_food_status_expiry (status, expires_at),
  INDEX idx_food_restaurant (restaurant_id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS claims (
  claim_id INT AUTO_INCREMENT PRIMARY KEY,
  food_item_id INT NOT NULL UNIQUE,
  ngo_id INT NOT NULL,
  claimed_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  status ENUM('claimed','picked_up','cancelled') NOT NULL DEFAULT 'claimed',
  CONSTRAINT fk_claim_food FOREIGN KEY (food_item_id)
    REFERENCES food_items(food_item_id) ON DELETE CASCADE,
  CONSTRAINT fk_claim_ngo FOREIGN KEY (ngo_id)
    REFERENCES ngos(ngo_id) ON DELETE CASCADE
) ENGINE=InnoDB;

-- Optional test admin. Replace the password hash with a hash generated by Flask.
-- INSERT INTO admins (name, email, password_hash)
-- VALUES ('SafePlate Admin', 'admin@example.com', 'REPLACE_WITH_WERKZEUG_HASH');

-- Existing-schema migration helpers:
-- ALTER TABLE food_items ADD COLUMN expires_at DATETIME NULL;
-- UPDATE food_items SET expires_at = DATE_ADD(created_at, INTERVAL 2 HOUR) WHERE expires_at IS NULL;
-- ALTER TABLE food_items MODIFY expires_at DATETIME NOT NULL;
-- ALTER TABLE food_items CHANGE item_id food_item_id INT AUTO_INCREMENT;
-- ALTER TABLE claims CHANGE item_id food_item_id INT NOT NULL;
